### ISSUE TITLE
Swift 2.3

### ISSUE THREAD

**Issue by sneps85** [sochalewski/UIImageViewAlignedSwift#12]
Will there be Swift 2.3 support?

**Comment by sochalewski** [comment]
@sneps85 Current `master` works well with Swift 2.3. It'll be available on `swift-2x` branch, but I strongly recommend you use Swift 3.0 as only this branch is under maintenance.

**Comment by sochalewski** [comment]
@sneps85 Just released 0.3.0 for Swift 3.0. Swift 2.3 compatible release can be found on `swift-2.x` branch.
