### ISSUE TITLE
Pod -> 0.1 installs 0.3.1

### ISSUE THREAD

**Issue by sneps85** [sochalewski/UIImageViewAlignedSwift#13]
i added in my pod file the following:

pod 'UIImageViewAlignedSwift', '~> 0.1'

but pod install installs version 0.3.1 which causes build failures as this version requires the newer swift versions.
Can you please check this?
Thank you very much

**Comment by sochalewski** [comment]
@sneps85 `~> 0.1` means version 0.1 and the versions up to 1.0, not including 1.0.
You need to use `~> 0.1.0`, which means version 0.1.0 and the versions up to 0.2.0, not including 0.2.0.

**Comment by sneps85** [comment]
ok thank you, my fault :)
