### ISSUE TITLE
Images are not displayed on a device but are shown in storyboard

### ISSUE THREAD

**Issue by alusev** [sochalewski/UIImageViewAlignedSwift#15]
I set up an image with aspect fill, clip to bounds and align left = on. When I see it in storyboard everything looks fine but when run the project, images disappear.

**Comment by alusev** [comment]
I fixed it. It seems that the problem appears with an Xcode update. This is how it used to be and it stopped working.
<img width="299" alt="captura de pantalla 2017-05-05 a la s 12 21 35" src="https://cloud.githubusercontent.com/assets/903378/25756747/7cb10f0c-318d-11e7-8d62-af4823c9637c.png">

Fixed (now it works perfect):
 
<img width="299" alt="captura de pantalla 2017-05-05 a la s 12 26 21" src="https://cloud.githubusercontent.com/assets/903378/25756920/29ce3d4a-318e-11e7-8aeb-9aa91653ea74.png">

**Comment by alusev** [comment]
I was wrong, images now appear but they don't get aligned.

**Comment by sochalewski** [comment]
@alusev Thank you for paying attention. In fact there was an issue that caused image to stop appearing, because I've noticed too. Even if module was right. 0.4.1 fixes that, not sure about aligning (works for me ;)), so please check 0.4.1 out and let me know.

**Comment by alusev** [comment]
0.4.1 fixed the issue. Thanks!
