### ISSUE TITLE
Dismissing ViewControllers above causes UI bug

### ISSUE THREAD

**Issue by LinusGeffarth** [sochalewski/UIImageViewAlignedSwift#16]
**EDIT**

It was not setting the image programmatically that causes the issue, but dismissing a UIViewController above the one with the image after presenting it as a popover i.e..
Below the original post.

---

I have set `UIImageViewAligned` as my `UIImageView`'s class in storyboard, enabled right alignment and provided an image:

![screen shot 2017-10-30 at 14 18 32](https://user-images.githubusercontent.com/9455439/32172831-471305ea-bd7d-11e7-8d46-c79503eff507.png)

It works just like it should until I update the image programmatically like:

    imageView.image = UIImage(named: "account.png")!

This results in the following UI:

![screen shot 2017-10-30 at 14 19 30](https://user-images.githubusercontent.com/9455439/32172948-a88c38e6-bd7d-11e7-8953-cefd01178719.png)

Any idea why this happens & what I can do about it?

**Comment by sochalewski** [comment]
Looks like a bug. Thank you for your report, I'll investigate this within a few days. Could you please let me know which version do you use?

**Comment by LinusGeffarth** [comment]
Cool, thanks for taking care of this. I am currently on 0.5.0 and am using CocoaPods

**Comment by sochalewski** [comment]
@LinusGeffarth Just checked it out on iOS 11.1 and it seems to work just fine.
Take a look at the example I provided and compare it to your code.

[Demo](https://github.com/sochalewski/UIImageViewAlignedSwift/files/1437689/Test.zip)

**Comment by LinusGeffarth** [comment]
Hm, true. I figured when I set the image at some other point in my code, it does work w/o issues. It's probably about constraint refreshes I'm committing...
Thanks anyway!

**Comment by LinusGeffarth** [comment]
I've found the issue. Whenever you present a view controller on the view controller with the image view inside, and then dismiss it, the bug occurs. Check out the zip. Make sure to run it on an iPad, I've only experienced the issue with popovers.

[Test.zip](https://github.com/sochalewski/UIImageViewAlignedSwift/files/1437868/Test.zip)

**Comment by sochalewski** [comment]
I got it. Just released `0.5.1-beta` which resolves the issue, but may implement some new :)

To check it out change one of lines in your `Podfile` to
```pod 'UIImageViewAlignedSwift', '~> 0.5.1-beta'```
and then run `pod update --repo-update`.

**Comment by LinusGeffarth** [comment]
Awesome! I have updated to the beta and it works for the test project. However, for mine, it doesn't. I'm still debugging.
My structure:
```
Nav
    -> PageController
        -> Nav
            -> VC
                -> TabBar
                    -> Nav
                        -> VC
                            -> VC over full screen, w/ image view
                                -> Popover that's to be dismissed
```
Maybe that helps...

---

**Edit**

I only experience it in one VC so it's probably some other issue. Geez. Ha!

**Comment by sochalewski** [comment]
Wow, it looks crazy :) I have no idea at this moment, but I'll try resolve this. Nevertheless feel free to post your solution or pull request when you got something 👍

**Comment by lkravchuk** [comment]
I was able to reproduce the bug on the iOS11+ only and it seems that it's still there even in updated 0.5.1-beta. ImageView was added to storyboard with aspect Fit content mode and left alignment ON
You can replicate this behavior by using the system alerts with 0.5.0
Or by pushing some view with 0.5.1-beta
Trying to figure out how to fix it

**Update**
Well, still have no idea why, but it seems that on iOS 11 any changes on parent view controller causes the showing of `image` and `realImageView?.image` at the same time, so using the last fix from beta branch + re-assigning the image inside `didMoveToWindow()` fixed it for me, but would be great if to test this more to be sure that there will be no more side-effects.

**Comment by ToniTornado** [comment]
I used the latest beta branch but still had this issue. To reproduce it, I had to start the app, dismiss it (home button), bring it to foreground and then rotate the view.

Maybe this helps someone debugging it...

**Comment by Niegazowana** [comment]
Hi! I opened a PR to solve this issue
