### ISSUE TITLE
iOS 11 specific code question.

### ISSUE THREAD

**Issue by jzeferino** [sochalewski/UIImageViewAlignedSwift#21]
Hello there, I was porting this code to Xamarin.iOS I was wondering why is the iOS 11 [specific code ](https://github.com/sochalewski/UIImageViewAlignedSwift/commit/549815525b1c114b86e7f38250962552f7fc0b86#diff-d41456b026f29d9ece945bce749739c9) needed.

Can you elaborate please?

**Comment by sochalewski** [comment]
Hello, this is related to https://github.com/sochalewski/UIImageViewAlignedSwift/issues/16

**Comment by jzeferino** [comment]
Thank you for clarify.
