### ISSUE TITLE
Image duplication in iOS 13b1

### ISSUE THREAD

**Issue by sigursalt** [sochalewski/UIImageViewAlignedSwift#23]
Hi,

First off thanks much for this library!

iOS13b1 is causing a duplication of the image when using a UIImageViewAligned.  If you align the image you'll see the image aligned the way you want, but you'll also see the same image in the center of the view.    (both in simulator and device)

If you use UIImageViewAligned and don't align it you'll see a duplication of the image right under the UIImageView it creates.

I've attached a screenshot from Reveal below.   Just a simple project with one image.  

The bottom layer is referenced as UIImageViewAlignedSwift.UIImageViewAligned, and the top is the UIImageView the library creates.

![Screen Shot 2019-06-06 at 8 09 55 AM](https://user-images.githubusercontent.com/6842082/59031727-85709100-8832-11e9-9977-173b6410c344.png)

Thanks again!

**Comment by yuriandryu** [comment]
I have the same problem!
If the image is aligned, 2 images appear, one aligned and the second in the center of the original. Please pack it as soon as possible!

**Comment by yuriandryu** [comment]
import UIImageViewAlignedSwift
Could not find module 'UIImageViewAlignedSwift' for target 'armv7-apple-ios'; found: arm64, arm64-apple-ios

**Comment by ToshMeston** [comment]
Same.

**Comment by skytramontanor** [comment]
Same
