### ISSUE TITLE
Image duplication in iOS 13b5 [BUG]

### ISSUE THREAD

**Issue by degello** [sochalewski/UIImageViewAlignedSwift#26]
The issue is still present in beta version 5 of iOS 13

**Comment by pgrundner** [comment]
Thin behavior is also present on iOS12, so i don't think it is needed to complain on each ios 13 beta :)

**Comment by ajkerfaisal** [comment]
This behavior is happening in iOS 13.1 (as of today) but doesn't happen in iOS 12.2

**Comment by pgrundner** [comment]
Hi,

i don’t agree with you. I recently (just a few seconds ago) had a try with iOS 11.4 and had this rotation behavior.
maybe its relevant to use transparent png’s?

kind regards,
Peter

> Am 30.09.2019 um 12:54 schrieb Mohammad Faisal <notifications@github.com>:
> 
> This behavior is happening in iOS 13.1 (as of today) but doesn't happen in iOS 12.2

**Comment by ajkerfaisal** [comment]
More info about my case:
Remote transparent png's and they are in UITableViewCell. The problem occurs when scrolling backward in UITableView.

**Comment by skyparentile** [comment]
Fixed removing 
` if #available(iOS 11, *) {
            super.image = nil
        }`

everywhere (didMoveToSuperview,didMoveToWindow,updatelayout, etc)

This fix also for iOS11

**Comment by DkSuperMan** [comment]
I fix the bug. Please don't use override image, because the iOS13 system also want  to use the image to draw layer content.

**Comment by FabianBartels** [comment]
I also encountered this bug with version 0.7.0 when importing the repo via pods.
My workaround was to include it without cocoa pods by copy & paste the code.
I did not figured out why this happened but this workaround helped. 

Thanks for providing such a nice repo though.

**Comment by sochalewski** [comment]
@FabianBartels That's because `master` contains a fix, but new release has not been pushed to the repository. I've released 0.8.0, so now you can easily get it through CocoaPods.
