### ISSUE TITLE
Property alignTop

### ISSUE THREAD

**Issue by orojasanchez** [sochalewski/UIImageViewAlignedSwift#4]
Hi, I'm a little new on the subject of iOS and not quite understand some things. It happens the following:
1. You install the UIImageViewAlignedSwift library in my xcode project with Pods.
2. I Add a imageView my storyboard.
3. Change the class of the image view to UIImageViewAligned
4. Add the property alignTop boolean true.

The problem is that when I run the app the compiler tells me that there is no such property. can someone please help me?

**Comment by orojasanchez** [comment]
I now understand how it is, in this case the property is not used but is done through swift code with the lines on the object:

import UIKit
import UIImageViewAlignedSwift

class ViewController: UIViewController
{
    @IBOutlet weak var bgBackground: UIImageViewAligned!

```
override func viewDidLoad() {
    super.viewDidLoad()

    bgBackground.alignment.insert(UIImageViewAlignmentMask.TopLeft)
}
```

}

**Comment by sochalewski** [comment]
Hi @orojasanchez,
You're right, I dropped `alignTop` when porting to Swift.

This way could work just fine, but inserting is not really safe when you want to change this property later. Instead try this:
`bgBackground.alignment = .TopLeft`

**Comment by orojasanchez** [comment]
Thanks
