### ISSUE TITLE
Any example?

### ISSUE THREAD

**Issue by xuanzi23** [sochalewski/UIImageViewAlignedSwift#7]
Hi , I am new to swift.
I looking for the image can align top when the image view is set to Aspect Fill in storyboard inside the tableview.

so how i call the align top function for this pod?

**Comment by sochalewski** [comment]
Hi,

The same question was asked in #4 and #6. Hope that it'll help you.

**Comment by xuanzi23** [comment]
But my is in tableview so i need to declare at table cell swift file or the tableview controller file?

**Comment by xuanzi23** [comment]
![screen shot 2016-05-20 at 3 08 20 pm](https://cloud.githubusercontent.com/assets/19340910/15420024/ca52fa04-1e9c-11e6-884e-6855e5dd35c9.png)

got this problem

**Comment by sochalewski** [comment]
That should work well. Are you sure `jobImage` is an `UIIimageViewAligned` class object?

**Comment by xuanzi23** [comment]
it is UIImageViewAligned class object or this cannot work with the image view download from server?
which is SDWebImage

**Comment by sochalewski** [comment]
It should work well doesn't matter where the picture comes from. As I see your screenshot it compiles, but crashes on execute, right?
I've got no idea what's wrong. Could you try clean your project (⇧⌘K) and its build folder (⌥⇧⌘K)?

BTW According to requests I'm going to bring back support for setting it via storyboard. So you can look forward to next version and check it out if it solves your issue.

**Comment by xuanzi23** [comment]
Sure no problem looking forward to the next version

**Comment by sochalewski** [comment]
it's available right now, so `pod update` and check it out in Interface Builder :)

**Comment by xuanzi23** [comment]
How to use this alignment interface builder?

**Comment by sochalewski** [comment]
First you have to be sure that your UIImageView has proper subclass and module.
![Identity inspector](http://i.imgur.com/v7wv6Ig.png)

Then using Attributes inspector just set whatever you want.
![Attributes inspector](http://i.imgur.com/tUxL9VB.png)

**Comment by xuanzi23** [comment]
This is so great!!!

**Comment by sochalewski** [comment]
Glad you like it :) Does your issue is solved right now and then can I close this thread?

**Comment by xuanzi23** [comment]
Ya, this solved my issue very well!
Thank you!!!

**Comment by gulzatique** [comment]
I think you should include it in read file, especially the part about 
1)choosing module = UIImageViewAlignedSwift
2) im swift file write import UIImageViewAlignedSwift
3) in storyboard drag UIView and set class UIImageViewAligned

thanks
